# Generated by Django 4.1.7 on 2023-02-17 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.TextField(max_length=50, verbose_name='название категории')),
                ('category_image', models.ImageField(null=True, upload_to='files/')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='номер счета')),
                ('name', models.TextField(default='не указан', max_length=30)),
                ('month', models.DateField(auto_now_add=True)),
                ('year', models.DateField(auto_now_add=True)),
                ('code', models.IntegerField(default=0, verbose_name='код оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='цена товара')),
                ('count', models.IntegerField(default=0, verbose_name='количество ')),
                ('date', models.DateField(auto_now_add=True)),
                ('title_product', models.TextField(max_length=50, verbose_name='название товара')),
                ('description', models.TextField(max_length=100, verbose_name='описание товара')),
                ('free_delivery', models.BooleanField(default=True)),
                ('product_picture', models.ImageField(null=True, upload_to='files/')),
                ('rating', models.IntegerField(default=0, verbose_name='счетчик покупок данного товара')),
                ('reviews', models.IntegerField(default=0, verbose_name='счетчик просмотров данного товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.categoryproduct', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='название')),
                ('value', models.TextField(max_length=50, verbose_name='значение')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='не указано', max_length=50, verbose_name='ФИО пользователя')),
                ('phone', models.CharField(blank=True, default='Не указано', max_length=30, null=True, unique=True, verbose_name='номер телефона')),
                ('email', models.EmailField(blank=True, default='Не указано', max_length=254, unique=True, verbose_name='email пользователя')),
                ('avatar', models.ImageField(null=True, upload_to='files/', validators=[store_app.models.UserProfile.validate_image])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='TagsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_name', models.TextField(max_length=50, verbose_name='тэг товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product', verbose_name='товар')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='Не указано', max_length=100, verbose_name='текст отзыва')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.userprofile', verbose_name='пользователь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_title_product_set', to='store_app.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.specifications', verbose_name='спецификация товара'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('delivery_type', models.TextField(default='не указан', max_length=30, verbose_name='способ доставки')),
                ('payment_type', models.TextField(default='не указан', max_length=30, verbose_name='способ оплаты')),
                ('total_cost', models.IntegerField(default=0, verbose_name='общая стоимость заказа')),
                ('status', models.TextField(default='не указан', max_length=30, verbose_name='статус оплаты')),
                ('city', models.TextField(default='не указан', max_length=30, verbose_name='город доставки')),
                ('address', models.TextField(default='не указан', max_length=30, verbose_name='адрес доставки')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product', verbose_name='товар')),
                ('user_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.userprofile', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'История покупок',
                'verbose_name_plural': 'Истории покупок',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='колличество  товаров в корзине')),
                ('price', models.IntegerField(default=0, verbose_name='общая стоимость  товаров в корзине')),
                ('date', models.DateField(auto_now_add=True)),
                ('free_delivery', models.BooleanField(default=False, verbose_name='наличие бесплатной доставки')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product', verbose_name='товар')),
            ],
        ),
        migrations.CreateModel(
            name='FilesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='files/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product', verbose_name='товар')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(related_name='product', through='store_app.Enrollment', to='store_app.product'),
        ),
        migrations.AddField(
            model_name='basket',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='store_app.userprofile'),
        ),
    ]
