# Generated by Django 4.1.6 on 2023-02-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryproduct',
            old_name='title_category',
            new_name='title',
        ),
    ]
