# Generated by Django 4.1.6 on 2023-02-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_rename_title_category_categoryproduct_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryproduct',
            old_name='category_image',
            new_name='image',
        ),
    ]
