# Generated by Django 4.1.6 on 2023-02-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_rename_category_image_categoryproduct_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title_product',
            new_name='title',
        ),
    ]
