# Generated by Django 4.1.7 on 2023-02-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_rename_title_product_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='image',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
